### ISSUE TITLE
Imputation of Expression Data

### ISSUE THREAD

**Issue by whitleyo** [welch-lab/liger#151]
Hi, given that a 'shared' latent factor space is found by the LIGER method, the final output of normalization is quantile normalized latent factor values in the non-reference batch and original latent factor values for the reference batch, I'm thinking about trying to reconstruct the reference and non-reference data using the loadings matrix mapping shared latent factors to expression values, as this would allow me to do signature scoring with a method such as [AUCell](http://bioconductor.org/packages/release/bioc/html/AUCell.html) or [gsva](https://bioconductor.org/packages/release/bioc/html/GSVA.html). 

I.E., let H be the matrix (mxp) of shared latent factor embeddings post normalization of non-reference data's embeddings, and let W be the (pxn) matrix mapping latent factors to the reference dataset's expression. Model is E<sub>i</sub> ~ H(W + V<sub>i</sub>), where i corresponds to dataset, and in the reconstruction I want to do, I'd like to have both datasets expressed as E = HW. I make the assumption that all biological signal of interest is within shared factors Do you see any problems with this approach from a theoretical/practical perspective?

**Comment by jw156605** [comment]
There's a much easier answer, which is that you can run gene set enrichment analysis directly on the metagenes (W, V, or W+V). We provide a function, runGSEA, that does this automatically. See our tutorial here: https://www.biorxiv.org/content/10.1101/2020.04.07.029546v1

**Comment by bschilder** [comment]
@jw156605 
I have a similar question @whitleyo regarding how to reconstruct the corrected gene x cell matrix. However in my case, I actually do need the full matrix, not just the metagenes, since I'll be using this to compute corrected cell-type means as CellTypeDataset reference input to [EWCE](https://github.com/NathanSkene/EWCE). @NathanSkene 

I've noticed [fastMNN](https://rdrr.io/github/LTLA/batchelor/man/fastMNN.html) does return the corrected matrix, but the authors advise against using this for downstream analyses. So I suppose my questions are twofold:
1) Is it valid to use LIGER's reconstructed matrix for downstream analyses, or are there statistical concerns I should be aware of?
2) If it is valid, how would I go about reconstructing the matrix properly in R?

Many thanks in advance, 
Brian
