### ISSUE TITLE
Integrating SCTransform-normalized data with LIGER

### ISSUE THREAD

**Issue by minigel** [welch-lab/liger#161]
Hello, I am wondering whether Seurat objects that have been normalized with SCTransform, rather than log-normalization, can be integrated with LIGER. The current vignette only describes the latter workflow: https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html

SCTransform outputs Pearson residuals that are used for integration with Seurat: (https://satijalab.org/seurat/v3.1/integration.html#sctransform). Can these residuals also be used as input to LIGER?

**Comment by skpalan** [comment]
Technically, yes. You can follow that tutorial starting from `RunOptimizeALS` as long as you have all the required data stored in the corresponding slots such as `scale.data`. 

**On the other hand, in order to perform `liger` correctly on your data, you need to manually make sure the Pearson residuals (which are stored in the scale.data slot) are non-negative.** 

Also since the tutorial and wrapper functions provided by `seurat-wrapper` are pretty old, we are currently connecting with Satija Lab to update both the package and tutorials. Please pay attention to future updates that are going to occur very recently.

**Comment by minigel** [comment]
Thank you so much for your response! I look forward to the updates on the tutorial and wrapper functions. In the meantime, would you be able to suggest manual transformations of the Pearson residuals that would be compatible with NMF/LIGER -- e.g. would the absolute values of the residuals be appropriate?

**Comment by minigel** [comment]
Thank you so much for your response! I look forward to the updates to the tutorial and wrapper functions. In the meantime, would you be able to suggest manual transformations of the Pearson residuals that would be compatible with NMF/LIGER -- e.g. would the absolute values of the residuals be appropriate?

**Comment by minigel** [comment]
Thank you so much for your response! I look forward to the updates to the tutorial and wrapper functions.

In the meantime, would you be able to suggest manual transformations of the Pearson residuals that would be compatible with NMF/LIGER -- e.g. would adding a constant to all the residuals be appropriate?
