### ISSUE TITLE
Cross species integration of data

### ISSUE THREAD

**Issue by mamtagiri** [welch-lab/liger#177]
HI guys I have datasets from 2 species that I would like to merge. There is no vignettes to guide us through. Moreover considering the difference in gene names nomenclature- how do we go about this?
thanks!
Mamta

**Comment by porchard** [comment]
Hi Mamta,

I'm not one of the LIGER authors but have done this using LIGER. For cross-species integration, you will need to make sure orthologous genes are given identical names across the species (which may involve, for example, converting all gene names to lower case since capitalization may differ across species' gene nomenclature). Beyond that, you would go about this in a similar manner as integrating e.g. two different RNA-seq datasets from the same species -- you would pass the matrices to LIGER as separate datasets (each species being a separate matrix).
