### ISSUE TITLE
scaleNotCenter doesn't seem to scale.

### ISSUE THREAD

**Issue by koenvandenberge** [welch-lab/liger#207]
I'm using `liger` 0.5.0 in R 3.6.2.

I'm trying to integrate RNA and ATAC-seq data following the provided [vignette](http://htmlpreview.github.io/?https://github.com/welch-lab/liger/blob/master/vignettes/Integrating_scRNA_and_scATAC_data.html).

In the preprocessing, the following steps are suggested
```
library(liger)
hbcData <- list(atac = atacCounts, 
                rna = rnaCounts)
hbcData <- createLiger(hbcData)

# preprocess
hbcData <- normalize(hbcData)
hbcData <- selectGenes(hbcData, datasets.use = 2)
hbcData <- scaleNotCenter(hbcData)
```

However, the `scaleNotCenter` doesn't finish. It seems that it simply doesn't scale. Here's a MWE:

## using 100 genes: runs and finishes

```
G = 1e2
rna = matrix(rnbinom(n=1e5, mu=10, size=1/2), nrow=G, ncol=1e3)
atac = matrix(rnbinom(n=1e5, mu=10, size=1/2), nrow=G, ncol=1e3)
rownames(rna) = rownames(atac) = paste0("gene", 1:G)


liger = createLiger(list(rna = rna, atac = atac))
# preprocess
hbcData <- normalize(hbcData)
hbcData <- selectGenes(hbcData, datasets.use = 2)
hbcData <- scaleNotCenter(hbcData)
```

## using 1000 genes: takes pretty long

```
G = 1e3
rna = matrix(rnbinom(n=1e6, mu=10, size=1/2), nrow=G, ncol=1e3)
atac = matrix(rnbinom(n=1e6, mu=10, size=1/2), nrow=G, ncol=1e3)
rownames(rna) = rownames(atac) = paste0("gene", 1:G)


liger = createLiger(list(rna = rna, atac = atac))
# preprocess
hbcData <- normalize(hbcData)
hbcData <- selectGenes(hbcData, datasets.use = 2)
hbcData <- scaleNotCenter(hbcData)
```

Given the simplicity of the purpose of the function, this doesn't seem to be expected, especially since in reality we easily have over 15K features in each of the RNA and ATAC matrices... I do and the function doesn't complete after > 10 hours. 
I have about 4K cells in each of the RNA and ATAC datasets.

# Session info

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] liger_0.5.0     patchwork_1.0.0 Matrix_1.2-18   cowplot_1.0.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       ica_1.0-2        plyr_1.8.5       pillar_1.4.3    
 [5] compiler_3.6.2   hdf5r_1.3.1      tools_3.6.2      iterators_1.0.12
 [9] bit_1.1-15.2     mclust_5.4.5     Rtsne_0.15       lifecycle_0.2.0 
[13] tibble_2.1.3     gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.3 
[17] doSNOW_1.0.18    rlang_0.4.10     foreach_1.4.7    DBI_1.1.0       
[21] ggrepel_0.8.1    parallel_3.6.2   dplyr_1.0.3      generics_0.0.2  
[25] vctrs_0.3.6      bit64_0.9-7      grid_3.6.2       tidyselect_1.1.0
[29] glue_1.4.2       R6_2.4.1         snow_0.4-3       irlba_2.3.3     
[33] ggplot2_3.3.2    purrr_0.3.3      magrittr_1.5     scales_1.1.0    
[37] codetools_0.2-16 riverplot_0.6    colorspace_1.4-1 munsell_0.5.0   
[41] crayon_1.3.4     FNN_1.1.3       
```

**Comment by skpalan** [comment]
Hi Koen, for the first issue, this is probaly because the `selectGenes()` function only found a few genes, can you try setting a lower threshhold for example using `selectGenes(hbcData, datasets.use = 2, var.thresh = 0.3)`? You can also check the number of the genes using `length(liger_object@var.genes)`. We would suggest 2k-3k genes for better results. Please let us know if this does not work. 
We will also add a warning message in the future version to remind users if the number of genes selected is too few. Thanks for bringing this up.

For the performance issue, I noticed that you were generating psudo-data using `rnbinom()` function, which is a function from `stats` package simulating negative binomial distribution. We would **NOT** suggest simulating single-cell data using this function because 1) the real data are usually very sparse, which means more than 70% of the data in the matrices are 0s; 2) single-cell data follows a much more complicated distribution instead of a negative binomial distribution. If you are interested in testing LIGER's performance on simulated data, we would suggest using the [Splatter](https://bioconductor.org/packages/release/bioc/html/splatter.html) package that can give a more credible simulation. You can also check **Figure 17** in our previous [paper](https://www.nature.com/articles/s41596-020-0391-8) in which we tested the performance of LIGER already.

**Comment by skpalan** [comment]
Ticket closed for now. Please feel free to create a new issue if you have any other problems.
