### ISSUE TITLE
setting axis limits with plotGeneDimRed

### ISSUE THREAD

**Issue by jessegmeyerlab** [welch-lab/liger#320]
I'm getting a group of cells at an extreme value of y that is only in one group and when I plot with "plotGeneDimRed" it makes it so the plot axes limits are not comparable and therefore hard to compare markers across. How can I set the axis ranges for this plotting? 
![image](https://github.com/user-attachments/assets/7e9b547c-acd3-4f1d-aa39-5a976863c6c8)

**Comment by mvfki** [comment]
Hi, 

Unfortunately, the axis limit setting is not built-in in LIGER's plotting function. However, the scatter plot functions are all built upon `ggplot2` so you can easily make the modification on your own after the `plotGeneDimRed()` function returns you the plot.

I assume what you shew there is done by setting `splitBy = "dataset", which makes scatter plot basing on each individual dataset (that's why axes are different for subplots), and then using some subplot combining function to combine them. I agree that having globally consistent axis limits is helpful for comparison across groups. 

Here's the work-around I can show you to manually resolve the problem. You'll want to keep the list that `plotGeneDimRed()` returned and start from there:

```R
plotList <- plotGeneDimRed(obj, "CNN1", splitBy = "dataset")
```

Each subplot can be accessed with `plotList[["CNN1.nameOfDataset"]]`. 

Then determine the range you want to manually set to both, which can be easily obtained with the following code chunk. I'm not sure if you have more than these two to be considered, so please note that thess ranges are for the whole integrated UMAP of all your datasets/groups. 

```R
globalXRange <- range(dimRed(obj, "UMAP")[,1])
globalYRange <- range(dimRed(obj, "UMAP")[,2])
```

Next, some shortcut syntax to apply the same change to all elements of a list object. 

```R
library(ggplot2)
plotListUpdated <- lapply(plotList, function(p) {
    p + scale_x_continuous(limits = globalXRange) + scale_y_continuous(limits = globalYRange)
})
```

Lastly, combine them back manually with your preferred tool:

```R
library(cowplot)
plot_grid(plotlist = plotListUpdated)
```
