### ISSUE TITLE
how to deal with batch in cross species comparison?

### ISSUE THREAD

**Issue by Li-ZhiD** [welch-lab/liger#322]
I have 2 datasets, from human and mouse, to be integrated. There is a batch effect within each dataset. Could some one tell me how to use liger to integrate these two datasets? thanks!

**Comment by mvfki** [comment]
The first thing you definitely want to do is to convert mouse gene names to their homologous ones in human genes. For example, rename mouse gene "Nkg7" to human homologous "NKG7". Most of the time it's just capitalizing the strings, but there are cases where the conversion might not be simple. For correctness, you may want to utilize some 3rd party tool and database like [biomart](https://useast.ensembl.org/info/data/biomart/index.html) to get it converted. The reason for the conversion is that LIGER technically need to find shared genes across each batch to jointly factorize the expression data.

After that, you can really just do the integration following our [basic tutorial](https://welch-lab.github.io/liger/articles/Integrating_multi_scRNA_data.html).

Another thing you might want to optionally consider is our extensional method UINMF, which not only uses the shared genes, but also make use of unshared genes (genes unique to each batch, or say, not in the intersection). This might help with making use of features unique to each species. See [paper](https://www.nature.com/articles/s41467-022-28431-4) or [tutorial](https://welch-lab.github.io/liger/articles/cross_species_vig.html) if you are interested in this method. 

Best,
Yichen

**Comment by Li-ZhiD** [comment]
Thank you! I have a seurat object, and its meta has a column of "batch" representing the batch, which contains information of donor for human and sampling batch for mouse. If I want to compare the human and mouse, are the following steps reasonable?  
- split the seurat according using split.by = "batch"
- go through the liger integration process

**Comment by mvfki** [comment]
I see. Since you have both datasets already in one Seurat object, I’d then assume you do have the same set of gene names even if they are different species. 

For using Seurat object, your steps look exactly right. For more guidance, you can also have a look at the documentation for [Iteroperation with Seurat](https://welch-lab.github.io/liger/articles/liger_with_seurat.html). 

Something like the following example should probably work:

```
ligerObj <- as.liger(seuratObj, datasetVar = "batch")
ligerObj <- normalize(ligerObj)
ligerObj <- selectGenes(ligerObj) # check parameter `thresh`
ligerObj <- scaleNotCenter(ligerObj)
ligerObj <- runINMF(ligerObj) # check parameter `k`
ligerObj <- quantileNorm(ligerObj) # check parameter `reference`
ligerObj <- runCluster(ligerObj) # check parameter `nNeighbors` and `resolution`
```

Just make sure to have a look at the basic tutorial linked to in my previous reply. There are a couple of parameters people usually need to tweak. I have them noted in the comments.

**Comment by Li-ZhiD** [comment]
Thank you!

Best!
