### ISSUE TITLE
Is name of this R package  liger or rliger?

### ISSUE THREAD

**Issue by highjws** [welch-lab/liger#323]
Hello, I need to install a package named "scCancer"  whose dependece pacakge is  "liger".   When I search this package by the name of "liger", it is your package. However, In your package's DESCRIPTION ,the package name is "rliger". So, I want to know if I got the package wrong—does the scCancer package depend on the liger package that is not the same as yours?

**Comment by theAeon** [comment]
its rliger. would have to look at sccancer as i don't know (but i'm fairly sure liger proper is...not a single cell analysis package)

**Comment by highjws** [comment]
Thanks for your reply! 
I will check the scCancer package and search for the liger package online. 
On the other hand, do you know that the R package liger is different from the current one?

**Comment by theAeon** [comment]
all i know about the r package liger is that its completely unrelated

**Comment by highjws** [comment]
Hello, I found the liger package I was looking for; it appears to be related to gene set enrichment functions.
Thanks for again!
After the issue is resolved, should this comment be closed? I'm a beginner using GitHub.

**Comment by theAeon** [comment]
yeah, you can also close it when you post the comment, like so

**Comment by highjws** [comment]
OK, thanks you very much!

**Comment by mvfki** [comment]
> scCancer

Unfortunately, I just went through their source code. They meant to refer to our package. See [this Issue](https://github.com/wguo-research/scCancer/issues/45#issuecomment-2294799028) from their repository, which shows you how to get things resolved. 

- The story is, at the very beginning stage of our package development, we were named by "liger". Due to the fact, which Andrew mentioned, there was already a CRAN released package that occupied this namespace, we had to rename our package, to "rliger". scCancer probably introduced our functionality into their package during that time, and NEVER check if their package still works in full. 

Yichen

**Comment by highjws** [comment]
Thanks for for your reply ! So, In summary, scCancer actually uses your package rliger, not any other package , but since the name "liger" was already taken when you developed your package, you changed it to rliger. However, scCancer hasn't updated their dependency from liger to rliger, Is that the overall situation?

**Comment by mvfki** [comment]
Exactly correct

**Comment by mvfki** [comment]
If you really have to use their package and use the option that calls our method. The only two way are to 1) download their source code and manually change anything "liger" to "rliger", and then install your modified version 2) send them messages or emails and push them to revise their code.

**Comment by highjws** [comment]
Ok, i get.  I'm very sorry to have disturbed you; I should have raised the issue under the scCancer project. 
Sorry for the disturbance, and thank you once again!
